%% Cleaning Car Data
% Instructions are in the task pane to the left. Complete and submit each task one at a time.
% This code sets up the activity.
% load  objectives.mat
% ob
% 

ob=["OBJECTIVE: TO OBTAIN VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT INFORMATION";
    "OBJECTIVE: GENERATE VEHICLE SIDE POLE CRASH PERFORMANCE INFORMATION";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: OBTAIN ATD AND VEHICLE DATA";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: TO OBTAIN VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT INFORMATION";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: REDUCE RISK OF SERIOUS & FATAL INJURY TO OCCUPANT OF PASSENGER CARS";
    "OBJECTIVE: TO OBTAIN VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT INFORMATION";
    "OBJECTIVE: TO OBTAIN VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT INFORMATION";
    "OBJECTIVE: TO GENERATE COMPARATIVE SIDE IMPACT PERFORMANCE INFORMATION";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT PERFORMANCE DATA";
    "OBJECTIVE: TO OBTAIN VEHICLE CRASHWORTHINESS AND OCCUPANT RESTRAINT INFORMATION"
    ]

%% Task 1
idx = contains(ob,"restraint","IgnoreCase",true)
restraint = ob(idx)
%% Task 2
resClean = erase(restraint,["OBJECTIVE:" "TO OBTAIN"])
%% Task 3
resClean = strtrim(resClean)